<?xml version="1.0" encoding="utf-8"?><Database Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Table Name="" Member="Class1s">
    <Type Name="Class1">
      <Column Name="Property1" Type="System.String" IsPrimaryKey="true" CanBeNull="false" />
      <Column Member="Id" Type="System.String" CanBeNull="false" />
    </Type>
  </Table>
</Database>