<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <DisableFody>true</DisableFody>
    <IsPackable>false</IsPackable>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="AnalyzerTesting.CSharp.Extensions" />
    <PackageReference Include="Verify.TUnit" />
    <PackageReference Include="TUnit.Core" />
    <PackageReference Include="TUnit.Assertions" />
    <PackageReference Include="TUnit.Engine" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\PropertyChanged\PropertyChanged.csproj" />
    <ProjectReference Include="..\PropertyChanged.Fody.Analyzer\PropertyChanged.Fody.Analyzer.csproj" NoWarn="NU1608" />
  </ItemGroup>
</Project>