<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net48;net10.0</TargetFrameworks>
    <ImplicitUsings>enable</ImplicitUsings>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Verify.ICSharpCode.Decompiler" />
    <PackageReference Include="Verify.TUnit" />
    <PackageReference Include="TUnit.Core" />
    <PackageReference Include="TUnit.Assertions" />
    <PackageReference Include="TUnit.Engine" />
    <PackageReference Include="Fody" PrivateAssets="all" />
    <PackageReference Include="FodyHelpers" />
    <PackageReference Include="PropertyChanging.Fody" PrivateAssets="all" />
    <ProjectReference Include="..\PropertyChanged\PropertyChanged.csproj" />
    <ProjectReference Include="..\PropertyChanged.Fody.Analyzer\PropertyChanged.Fody.Analyzer.csproj" PrivateAssets="all" ReferenceOutputAssembly="false" OutputItemType="Analyzer" />
    <WeaverFiles Include="$(SolutionDir)$(SolutionName).Fody\bin\$(Configuration)\netstandard2.0\$(SolutionName).Fody.dll" />
    <CompilerVisibleProperty Include="PropertyChangedAnalyzerConfiguration" />
  </ItemGroup>
  <PropertyGroup>
    <PropertyChangedAnalyzerConfiguration>
      <IsCodeGeneratorDisabled>false</IsCodeGeneratorDisabled>
      <EventInvokerName>OnPropertyChanged</EventInvokerName>
    </PropertyChangedAnalyzerConfiguration>
  </PropertyGroup>
</Project>