<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <EnforceExtendedAnalyzerRules>true</EnforceExtendedAnalyzerRules>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.CodeAnalysis.Analyzers" VersionOverride="5.9.0" PrivateAssets="all" IsPinned="true" Justification="Stick with this version for compatibility with older VS versions"/>
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" VersionOverride="5.9.0" PrivateAssets="all" IsPinned="true" Justification="Stick with this version for compatibility with older VS versions"/>
    <PackageReference Include="Nullable.Extended.Analyzer" PrivateAssets="all" />
  </ItemGroup>
</Project>