using System.Collections.Immutable;
using Microsoft.CodeAnalysis;

#pragma warning disable CS0067
static class SourceGeneratorEngine
{
    internal static string GeneratorVersion = typeof(SourceGenerator).Assembly.GetName().Version.ToString();

    public static void GenerateSource(SourceProductionContext context, Configuration configuration, ImmutableArray<TypeContext> types)
    {
        // DebugBeep();

        var sourceFileHintName = "PropertyChanged.g.cs";

        if (configuration.IsCodeGeneratorDisabled)
        {
            context.AddSource(sourceFileHintName, "// Source generator is disabled by configuration.");
            return;
        }

        if (!types.Any())
            return;

        var eventInvokerName = configuration.EventInvokerName?.Trim().NullIfEmpty() ?? "OnPropertyChanged";

        var codeBuilder = new CodeBuilder();

        try
        {
            codeBuilder.AddPreamble();

            foreach (var classContext in types.Distinct(TypeContext.FullNameComparer))
            {
                GenerateCodeForClass(classContext, codeBuilder, eventInvokerName);
            }
        }
        catch (Exception ex)
        {
            codeBuilder.Add("/*");
            codeBuilder.Add($"GenerateSource failed: {ex}");
            codeBuilder.Add("*/");
        }

        context.AddSource(sourceFileHintName, codeBuilder.ToString());
    }

    static void AddPreamble(this CodeBuilder codeBuilder)
    {
        codeBuilder
            .Add("// <auto-generated/>")
            .Add("#nullable enable")
            .Add("#pragma warning disable CS0067")
            .Add("#pragma warning disable CS8019")
            .Add("using System.Diagnostics;")
            .Add("using System.CodeDom.Compiler;")
            .Add("using System.ComponentModel;")
            .Add("using System.Runtime.CompilerServices;");
    }

    static void GenerateCodeForClass(TypeContext typeContext, CodeBuilder codeBuilder, string eventInvokerName)
    {
        codeBuilder.Add();

        using (codeBuilder.AddBlock("namespace {0}", typeContext.ContainingNamespace))
        {
            var isSealed = typeContext.IsSealed;
            var hasBase = typeContext.HasBase;

            using (codeBuilder.AddBlock("partial {0}", typeContext.ContainingTypeDeclarations.Split('|')))
            {
                var baseDefinition = hasBase ? string.Empty : " : INotifyPropertyChanged";

                using (codeBuilder.AddBlock($"partial {typeContext.Declaration}{baseDefinition}"))
                {
                    AddGeneratedCodeAttribute(codeBuilder, false);
                    codeBuilder.Add("public event PropertyChangedEventHandler? PropertyChanged;");
                    codeBuilder.Add();

                    AddGeneratedCodeAttribute(codeBuilder, true);
                    using (codeBuilder.AddBlock($"{(isSealed ? "private" : "protected")} void {eventInvokerName}([CallerMemberName] string? propertyName = null)"))
                    {
                        if (isSealed)
                        {
                            codeBuilder.Add("PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(propertyName));");
                        }
                        else
                        {
                            codeBuilder.Add($"{eventInvokerName}(new PropertyChangedEventArgs(propertyName));");
                        }
                    }

                    codeBuilder.Add();

                    AddGeneratedCodeAttribute(codeBuilder, true);
                    using (codeBuilder.AddBlock($"{(isSealed ? "private" : "protected virtual")} void {eventInvokerName}(PropertyChangedEventArgs eventArgs)"))
                    {
                        codeBuilder.Add("PropertyChanged?.Invoke(this, eventArgs);");
                    }
                }
            }
        }
    }

    static void AddGeneratedCodeAttribute(CodeBuilder codeBuilder, bool isMethod)
    {
        codeBuilder.Add($"""[GeneratedCode("PropertyChanged.Fody", "{GeneratorVersion}"){(isMethod ? ", DebuggerNonUserCode" : "")}]""");
    }
}
